# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c44d3dab01398c17a85f971d4a9fa668ec190aa300072b75732c7ad9f2b1d7a58ab0c41bcd630c11ec0495d394744deb703111228fd42e41d733de9e8cf2559

test:
  secret_key_base: 4bcbb7930569d93a681d21a5dfd4c7e01311cb0dcb932a3af5cc8d53b014e0eed6ecdd8d42d1a5364e18f4e42c6dd2dd2d89bc90d84546418b7c888f70c0c6e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
